# Assignment 3: Pandas
Name : Akanksha Thakur
Roll No.: 1024160019

## Q1. Create a dataset as given in the table using a DataFrame

In [1]:
import pandas as pd

data = {
    "Tid": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "Refund": ["Yes", "No", "No", "Yes", "No", "No", "Yes", "No", "No", "Yes"],
    "Marital Status": ["Single", "Married", "Single", "Married", "Divorced",
                        "Married", "Divorced", "Single", "Married", "Single"],
    "Taxable Income": ["125K", "100K", "70K", "120K", "95K",
                        "60K", "220K", "85K", "75K", "90K"],
    "Cheat": ["No", "No", "No", "No", "Yes", "No", "No", "Yes", "No", "Yes"]
}

df = pd.DataFrame(data)
df

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125K    No
1    2     No        Married           100K    No
2    3     No         Single            70K    No
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     No        Married            60K    No
6    7    Yes       Divorced           220K    No
7    8     No         Single            85K   Yes
8    9     No        Married            75K    No
9   10    Yes         Single            90K   Yes

## Q2. Locate row 0, 4, 7 and 8 using the DataFrame created in Q1

In [2]:
df.loc[[0, 4, 7, 8]]

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125K    No
4    5     No       Divorced            95K   Yes
7    8     No         Single            85K   Yes
8    9     No        Married            75K    No

## Q3. Navigate the DataFrame and perform the following

**3.1** Select rows from index 3 to 7

In [3]:
df.iloc[3:8]

   Tid Refund Marital Status Taxable Income Cheat
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     No        Married            60K    No
6    7    Yes       Divorced           220K    No
7    8     No         Single            85K   Yes

**3.2** Select rows from index 4 to 8, and columns 2 to 4

In [4]:
df.iloc[4:9, 2:5]

  Marital Status Taxable Income Cheat
4       Divorced            95K   Yes
5        Married            60K    No
6       Divorced           220K    No
7         Single            85K   Yes
8        Married            75K    No

**3.3** Select all rows with column index 1 to 3 (include index 3 during selection)

In [5]:
df.iloc[:, 1:4]

  Refund Marital Status Taxable Income
0    Yes         Single           125K
1     No        Married           100K
2     No         Single            70K
3    Yes        Married           120K
4     No       Divorced            95K
5     No        Married            60K
6    Yes       Divorced           220K
7     No         Single            85K
8     No        Married            75K
9    Yes         Single            90K

## Q4. Read a csv file and display its first five rows
Dataset used: [Credit Card Approval Prediction](https://www.kaggle.com/datasets/uciml/iris) from Kaggle
(download `application_record.csv` — or any csv of your choice — and place it in the same folder
as this notebook, then update the `csv_path` variable below).

If you don't have the Kaggle dataset handy, this notebook also creates a small
sample csv (`sample_dataset.csv`) so that Q4 and Q5 can be run end-to-end.

In [6]:
import os

csv_path = "sample_dataset.csv"  # change this to the downloaded Kaggle csv path if available

if not os.path.exists(csv_path):
    sample = pd.DataFrame({
        "ID": [1, 2, 3, 4, 5, 6],
        "Name": ["Aman", "Riya", "Karan", "Simran", "Neha", "Rohit"],
        "Age": [23, 25, 22, 28, 24, 26],
        "City": ["Patiala", "Delhi", "Mumbai", "Chandigarh", "Jaipur", "Lucknow"],
        "Score": [88, 92, 79, 95, 85, 90]
    })
    sample.to_csv(csv_path, index=False)

csv_df = pd.read_csv(csv_path)
csv_df.head()

   ID    Name  Age        City  Score
0   1    Aman   23     Patiala     88
1   2    Riya   25       Delhi     92
2   3   Karan   22      Mumbai     79
3   4  Simran   28  Chandigarh     95
4   5    Neha   24      Jaipur     85

## Q5. From the csv file used in Q4, delete row 4 and delete column 3, then display the result
(Row/column positions are used here as in the question — index-based, 0-indexed.)

In [7]:
csv_df_modified = csv_df.drop(index=4)              # delete row with index 4
csv_df_modified = csv_df_modified.drop(csv_df_modified.columns[3], axis=1)  # delete column at position 3
csv_df_modified

   ID    Name  Age  Score
0   1    Aman   23     88
1   2    Riya   25     92
2   3   Karan   22     79
3   4  Simran   28     95
5   6   Rohit   26     90

## Q6. Create a sample dataset (employees.csv) and answer the following

In [8]:
employee_data = {
    "Employee_ID": [101, 102, 103, 104, 105],
    "Name": ["Alice", "Bob", "Charlie", "Dana", "Edward"],
    "Department": ["HR", "IT", "IT", "Marketing", "Sales"],
    "Age": [29, 34, 41, 28, 38],
    "Salary": [50000, 55000, 65000, 55000, 60000],
    "Years_of_Experience": [3, 8, 10, 2, 12],
    "Joining_Date": ["2020-03-15", "2017-07-19", "2013-05-01", "2021-02-10", "2010-11-23"],
    "Gender": ["Female", "Male", "Male", "Female", "Male"],
    "Bonus": [5000, 7000, 6500, 4500, 5000],
    "Rating": [4.5, 4.0, 4.8, 4.7, 3.9]
}

emp_df = pd.DataFrame(employee_data)
emp_df.to_csv("employees.csv", index=False)
emp_df

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,3,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,55000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-05-01,Male,6500,4.8
3,104,Dana,Marketing,28,55000,2,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-23,Male,5000,3.9

**a) Shape (number of rows and columns) of the DataFrame**

In [9]:
emp_df.shape

(5, 10)

**b) Summary of the DataFrame that includes the data types and non-null counts for each column**

In [10]:
emp_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      str
 2   Department           5 non-null      str
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      str
 7   Gender               5 non-null      str
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(5), str(4)
memory usage: 532.0 bytes

**c) Descriptive statistics**

In [11]:
emp_df.describe()

,Employee_ID,Age,Salary,Years_of_Experience,Bonus,Rating
count,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000
mean,103.000000,34.000000,57000.000000,7.000000,5600.000000,4.380000
std,1.581139,5.612486,5700.877125,4.358899,1083.974169,0.408656
min,101.000000,28.000000,50000.000000,2.000000,4500.000000,3.900000
25%,102.000000,29.000000,55000.000000,3.000000,5000.000000,4.000000
50%,103.000000,34.000000,55000.000000,8.000000,5000.000000,4.500000
75%,104.000000,38.000000,60000.000000,10.000000,6500.000000,4.700000
max,105.000000,41.000000,65000.000000,12.000000,7000.000000,4.800000

**d) Display the first 5 and last 3 rows of the dataset**

In [12]:
print("First 5 rows:")
display(emp_df.head())

print("Last 3 rows:")
display(emp_df.tail(3))

First 5 rows:

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,3,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,55000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-05-01,Male,6500,4.8
3,104,Dana,Marketing,28,55000,2,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-23,Male,5000,3.9

Last 3 rows:

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
2,103,Charlie,IT,41,65000,10,2013-05-01,Male,6500,4.8
3,104,Dana,Marketing,28,55000,2,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-23,Male,5000,3.9

**e) Calculate the following statistics from the dataset**

In [13]:
avg_salary = emp_df["Salary"].mean()
total_bonus = emp_df["Bonus"].sum()
youngest_employee = emp_df.loc[emp_df["Age"].idxmin(), "Name"]
highest_rated_employee = emp_df.loc[emp_df["Rating"].idxmax(), "Name"]

print("i.   Average salary of employees:", avg_salary)
print("ii.  Total bonus paid to all employees:", total_bonus)
print("iii. Youngest employee:", youngest_employee)
print("iv.  Highest performance rating employee:", highest_rated_employee)

i.   Average salary of employees: 57000.0
ii.  Total bonus paid to all employees: 28000
iii. Youngest employee: Dana
iv.  Highest performance rating employee: Charlie

**f) Sort the DataFrame by the Salary column in descending order**

In [14]:
emp_df_sorted = emp_df.sort_values(by="Salary", ascending=False)
emp_df_sorted

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
2,103,Charlie,IT,41,65000,10,2013-05-01,Male,6500,4.8
4,105,Edward,Sales,38,60000,12,2010-11-23,Male,5000,3.9
1,102,Bob,IT,34,55000,8,2017-07-19,Male,7000,4.0
3,104,Dana,Marketing,28,55000,2,2021-02-10,Female,4500,4.7
0,101,Alice,HR,29,50000,3,2020-03-15,Female,5000,4.5

**g) Add a new column that categorizes employees based on their performance rating**

In [15]:
def categorize_rating(rating):
    if rating >= 4.5:
        return "Excellent"
    elif rating >= 4.0:
        return "Good"
    else:
        return "Average"

emp_df["Performance_Category"] = emp_df["Rating"].apply(categorize_rating)
emp_df

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
0,101,Alice,HR,29,50000,3,2020-03-15,Female,5000,4.5,Excellent
1,102,Bob,IT,34,55000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-05-01,Male,6500,4.8,Excellent
3,104,Dana,Marketing,28,55000,2,2021-02-10,Female,4500,4.7,Excellent
4,105,Edward,Sales,38,60000,12,2010-11-23,Male,5000,3.9,Average

**h) Identify missing values in the DataFrame**

In [16]:
emp_df.isnull().sum()

Employee_ID             0
Name                    0
Department              0
Age                     0
Salary                  0
Years_of_Experience     0
Joining_Date            0
Gender                  0
Bonus                   0
Rating                  0
Performance_Category    0
dtype: int64

**i) Rename the Employee_ID column to ID**

In [17]:
emp_df = emp_df.rename(columns={"Employee_ID": "ID"})
emp_df.columns

Index(['ID', 'Name', 'Department', 'Age', 'Salary', 'Years_of_Experience',
       'Joining_Date', 'Gender', 'Bonus', 'Rating', 'Performance_Category'],
      dtype='str')

**j) Find all employees who have more than 5 years of experience AND belong to the IT department**

In [18]:
experienced_it_employees = emp_df[(emp_df["Years_of_Experience"] > 5) & (emp_df["Department"] == "IT")]
experienced_it_employees

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
1,102,Bob,IT,34,55000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-05-01,Male,6500,4.8,Excellent

**k) Modify the dataset by adding a new column, Tax, which deducts 10% of the Salary**

In [19]:
emp_df["Tax"] = emp_df["Salary"] * 0.10
emp_df

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category,Tax
0,101,Alice,HR,29,50000,3,2020-03-15,Female,5000,4.5,Excellent,5000.0
1,102,Bob,IT,34,55000,8,2017-07-19,Male,7000,4.0,Good,5500.0
2,103,Charlie,IT,41,65000,10,2013-05-01,Male,6500,4.8,Excellent,6500.0
3,104,Dana,Marketing,28,55000,2,2021-02-10,Female,4500,4.7,Excellent,5500.0
4,105,Edward,Sales,38,60000,12,2010-11-23,Male,5000,3.9,Average,6000.0

**l) Save the modified DataFrame (with added columns) to a new CSV file**

In [20]:
emp_df.to_csv("employees_modified.csv", index=False)
print("Saved to employees_modified.csv")

Saved to employees_modified.csv